[package]
name = "wav_file_decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.21", features = ["derive"] }
core-graphics = "0.24.0"
num = "0.4.3"
sdl2 = "0.37.0"
